altan/login/__init__.py
from flask import Blueprint

giris = Blueprint("giris", __name__)

from altan.login import routes

altan/login/routes.py
from flask import render_template, request, redirect, url_for, flash, session
from altan.extensions import db, login_manager, UserMixin, login_required, login_user, logout_user
from altan.login import giris
from altan.models import Program, Destek
from urllib.parse import urlparse, urljoin

login_manager.login_view = "giris.login"
login_manager.login_message = ""


def is_safe_url(target):
    ref_url = urlparse(request.host_url)
    test_url = urlparse(urljoin(request.host_url, target))
    return test_url.scheme in ("http", "https") and ref_url.netloc == test_url.netloc


class User(UserMixin, db.Model):
    id = db.Column(db.Integer, primary_key=True, nullable=False)
    username = db.Column(db.String(20), nullable=False)
    password = db.Column(db.String(20), nullable=False)


@login_manager.user_loader
def load_user(user_id):
    return User.query.get(int(user_id))


@giris.route('/login', methods=["GET", "POST"])
def login():
    if request.method == 'POST':
        username = request.form.get("username")
        password = request.form.get("password")
        user = User.query.filter(User.username == username).first()
        if not user:
            flash('Kullanıcı adı hatalı', 'danger')
            return render_template("login.html")
        if not user.password == password:
            flash('Şifre Hatalı', 'danger')
            return render_template("login.html")
        login_user(user, remember=True)
        if "next" in session and session["next"]:
            if is_safe_url(session["next"]):
                return redirect(session["next"])
        return redirect(url_for("main.index"))
    session["next"] = request.args.get("next")
    return render_template("login.html")


@giris.route('/logout')
@login_required
def log_out():
    logout_user()
    return redirect(url_for("giris.login"))


@giris.route('/parametreler/')
def parametreler():
    users = User.query.all()
    programlar = Program.query.all()
    program_sayisi = len(programlar)
    destekler = Destek.query.all()
    defaults = dict(users=users, programlar=programlar, destekler=destekler, sayi=program_sayisi)
    return render_template("parametre.html", defaults=defaults)


@giris.route('/parametreler/ekle/kullanici/', methods=["GET", "POST"])
def parametreler_kullanici_ekle():
    if request.method == 'POST':
        username = request.form.get("kullaniciisimekle")
        password = request.form.get("kullanicisifreekle")
        new_user = User(username=username, password=password)
        db.session.add(new_user)
        db.session.commit()
        flash('Kullanıcı Veritabanına Eklenmiştir', 'success')
        return redirect(url_for("giris.parametreler"))
    else:
        flash('Veriler Eklenemedi', 'danger')
        return redirect(url_for("giris.parametreler"))


# @giris.route('/parametreler/sil/program/<int:user_id>/')
# def parametreler_kullanici_sil(user_id):
#     user = User.query.filter(User.id == user_id).first()
#     if user.name == "altan":
#         flash('Altan Kullanıcısı is GOD, cant delete', 'success')
#         return redirect(url_for("giris.parametreler"))
#     else:
#         db.session.delete(user)
#         db.session.commit()
#         flash('Seçilen Kullanıcı Veritabanından Silinmiştir', 'success')
#         return redirect(url_for("giris.parametreler"))


@giris.route('/parametreler/ekle/program/<int:sayi>/', methods=["GET", "POST"])
def parametreler_program_ekle(sayi):
    if request.method == 'POST':
        program_ismi = request.form.get("programisimekle")
        new_program = Program(isim=program_ismi, id = sayi+1)
        db.session.add(new_program)
        db.session.commit()
        flash('Program Veritabanına Eklenmiştir', 'success')
        return redirect(url_for("giris.parametreler"))
    else:
        flash('Veriler Eklenemedi', 'danger')
        return redirect(url_for("giris.parametreler"))


@giris.route('/parametreler/guncelle/program/<int:program_id>/', methods=["GET", "POST"])
def parametreler_program_guncelle(program_id):
    program = Program.query.filter(Program.id == program_id).first()
    if request.method == 'POST':
        program_ismi = request.form.get("programguncelle")
        program.isim = program_ismi
        db.session.commit()
        flash('Program Verileriniz Güncellenmiştir', 'primary')
        return redirect(url_for("giris.parametreler"))
    else:
        flash('Veriler Güncellenemedi', 'danger')
        return redirect(url_for("giris.parametreler"))


@giris.route('/parametreler/sil/program/<int:program_id>/')
def parametreler_program_sil(program_id):
    program = Program.query.filter(Program.id == program_id).first()
    db.session.delete(program)
    db.session.commit()
    flash('Seçilen Program Veritabanından Silinmiştir', 'success')
    return redirect(url_for("giris.parametreler"))


@giris.route('/parametreler/ekle/destek/', methods=["GET", "POST"])
def parametreler_destek_ekle():
    if request.method == 'POST':
        destek_ismi = request.form.get("destekisimekle")
        new_destek = Destek(isim=destek_ismi)
        db.session.add(new_destek)
        db.session.commit()
        flash('Destek Veritabanına Eklenmiştir', 'success')
        return redirect(url_for("giris.parametreler"))
    else:
        flash('Veriler Eklenemedi', 'danger')
        return redirect(url_for("giris.parametreler"))


@giris.route('/parametreler/guncelle/destek/<int:destek_id>/', methods=["GET", "POST"])
def parametreler_destek_guncelle(destek_id):
    destek = Destek.query.filter(Destek.id == destek_id).first()
    if request.method == 'POST':
        destek_ismi = request.form.get("destekguncelle")
        destek.isim = destek_ismi
        db.session.commit()
        flash('Destek Verileriniz Güncellenmiştir', 'primary')
        return redirect(url_for("giris.parametreler"))
    else:
        flash('Veriler Güncellenemedi', 'danger')
        return redirect(url_for("giris.parametreler"))


@giris.route('/parametreler/sil/destek/<int:destek_id>/')
def parametreler_destek_sil(destek_id):
    destek = Destek.query.filter(Destek.id == destek_id).first()
    db.session.delete(destek)
    db.session.commit()
    flash('Seçilen Destek Veritabanından Silinmiştir', 'success')
    return redirect(url_for("giris.parametreler"))

altan/templates/butce_sorgu.html
{% extends "layout.html" %} 
{% block head %}
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.9.4/Chart.min.js"></script>
{% endblock head %}
{% block title %}Bütçe Sorgulama{% endblock %}
{% block body %}

{% import "macros.html" as m %}

{{m.ust_bilgi("Bütçe Sorgulama")}}

<div class="container-fluid">
    <form class="row g-2 pb-2" action="{{url_for('kisisel.butce_sorgula')}}" method="POST">
        <div class="col">   
            {% call m.select("Başlangıç Tarihi","baslangic_yil") %}
                {% for yil in defaults["yillar"] %}
                    <option value="{{yil}}" {{'selected' if yil == defaults['bas_yil'] }}>{{yil}}</option>
                {% endfor %}
            {% endcall %}
        </div>
        <div class="col">
            {% call m.select("Bitiş Tarihi","bitis_yil") %}
                {% for yil in defaults["yillar"] %}
                    <option value="{{yil}}" {{'selected' if yil == defaults['bit_yil'] }}>{{yil}}</option>
                {% endfor %}
            {% endcall %}
        </div>    
        <div class="col">
            {% call m.select("Gelir","gelir-sorgu") %}
                {% for gelir_value, gelir_label in packed_gelirler %}
                    <option value="{{gelir_value}}" {{'selected' if gelir_value == defaults['gelir_sor'] }}>{{gelir_label}}</option>
                {% endfor %}
            {% endcall %}
        </div> 
        <div class="col">
            {% call m.select("Gider","gider-sorgu") %}
                {% for gider_value, gider_label in packed_giderler %}
                <option value="{{gider_value}}" {{'selected' if gider_value == defaults['gider_sor'] }}>{{gider_label}}</option>
                {% endfor %}
            {% endcall %}
        </div>
        {{m.button_class("Sorgula","fas fa-search","btn btn-outline-secondary btn-block")}}
    </form>

    <div class="row g-2 pb-2 pt-2">
        <div class="col-md-6">
            <h5>Gelir Grafiği</h5>
            <canvas id="myChart"></canvas>            
            <script>
                var ctx = document.getElementById('myChart').getContext('2d');
                var myChart = new Chart(ctx, {
                    type: 'line',
                    data: {
                        labels: {{ defaults['ay_sayisi']|tojson|safe }},
                        datasets: [{
                            label: '# Ay',
                            data: {{ defaults['gelir_tablo']|tojson|safe }},
                        }]
                    },
                    options: {
                        scales: {
                            yAxes: [{
                                ticks: {
                                    beginAtZero: true
                                }
                            }]
                        }
                    }
                });
            </script>
            <br>
            <h5> - Toplam Gelir - {{defaults['toplam_gelir']}}</h5>
            <h5> - Ortalama Gelir - {{defaults['gelir_ort']}}</h5>
        </div>

        <div class="col-md-6">
            <h5>Gider Grafiği</h5>
            <canvas id="myChart2"></canvas>
            <script>
                var ctx = document.getElementById('myChart2').getContext('2d');
                var myChart = new Chart(ctx, {
                    type: 'line',
                    data: {
                        labels: {{ defaults['ay_sayisi']|tojson|safe }},
                        datasets: [{
                            label: '# Ay',
                            data: {{ defaults['gider_tablo']|tojson|safe }},
                        }]
                    },
                    options: {
                        scales: {
                            yAxes: [{
                                ticks: {
                                    beginAtZero: true
                                }
                            }]
                        }
                    }
                });
            </script>
            <br>
            <h5> - Toplam Gider - {{defaults['toplam_gider']}}</h5>
            <h5> - Ortalama Gider - {{defaults['gider_ort']}}</h5>
            <h5>{{perc}}</h5>
        </div>
    </div>
</div>


{% endblock body %}

altan/templates/diziler.html
{% extends "layout.html" %} 
{% block head %}
  <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/v/bs4/dt-1.10.23/fc-3.3.2/fh-3.1.8/r-2.2.7/sc-2.0.3/sl-1.3.1/datatables.min.css"/>
{% endblock head %}
{% block title %}Diziler{% endblock title %}
{% block body %}
{% import "macros.html" as m %}
{{m.ust_bilgi("Diziler","fas fa-icons")}}

<!-- DİZİ EKLE -->
<div class="container-fluid">
  <div class="row">
    <button type="submit" class="btn btn-outline-secondary btn-lg btn-block" data-toggle="modal" data-target="#diziekle"><i class="fas fa-plus"></i>Dizi Ekle</button>                                                
    {{m.model_acilis("diziekle","dizilerModalLabel")}}
      {{m.model_header("Dizi Ekle","dizilerModalLabel")}}
        <form action="{{url_for('kisisel.dizi_ekle')}}" method="POST">
          {{m.input_group_modal("İsim","text","diziisimekle","")}}
          {{m.input_group_modal("Çıkış Tarihi","text","dizicikistarihiekle","")}}
          {{m.input_group_modal("Tur","text","diziturekle","")}}
          {{m.input_group_modal("Son İzlenen","text","dizisonizlenenekle","")}}
          {{m.input_group_modal("IMDB Puanı","number","diziimdbpuaniekle","")}}
          {{m.input_group_modal("IMDB Link","text","diziimdblinkekle","")}}
          {{m.input_group_modal("Puanım","number","dizipuanimekle","")}}
          {% call m.select_modal("Dizi Durum","dizidurumekle") %}
            <option value="Devam Ediyor" selected>Devam Ediyor</option>
            <option value="Tamamlandı" >Tamamlandı</option>
          {% endcall %}
          {{m.button_resimsiz("KAYDET")}}
        </form>
    {{m.model_kapanis()}}
    <div class="col mt-4">
      {{m.input_group_id("Arama","fas fa-search","text","dizi_ara","dizi_ara","")}}
    </div>
  </div>
</div>

<!-- DİZİ BİLGİLERİ TABLOSU -->
<div class="container-fluid">
  <div class="row">
    <div class= "col-md-12 mt-2">
      <table id="diziler" class="table table-hover table-striped table-sm" cellspacing="0" width="100%">
        {{m.tablehead_10("","İsim","Çıkış Tarihi","Tur","Son İzlenen","IMDB Puanı","IMDB Link","Puanım","İzleme Durumu","İşlemler")}}
        <tbody>  
          {% for dizi in diziler|sort(reverse=true, attribute="cikis_tarihi") %}  
          <tr>
            <th>{{loop.index}}</th>
            <th>{{dizi.isim}}</th>
            <td>{{dizi.cikis_tarihi}}</td>
            <td>{{dizi.tur}}</td>
            <td>{{dizi.son_izlenen}}</td>
            <td>{{dizi.imdb_puani}}</td>
            <td>
                <a type="button" class="btn btn-outline-secondary btn-sm" target="_blank" rel="noopener noreferrer" href="{{dizi.imdb_link}}"><span class="fab fa-imdb"></span></a>
            </td>
            <td>{{dizi.mehmet_puan}}</td>
            <td>{{dizi.ddurum}}</td>
            <td style="text-align:center">
              <button type="submit" class="btn btn-outline-secondary btn-sm" data-toggle="modal" data-target="#myOutput{{dizi.id}}"><span class="fas fa-pen"></button>                   
              <div class="modal fade" id="myOutput{{dizi.id}}" tabindex="-1" role="dialog" aria-labelledby="dizilerguncelModalLabel" aria-hidden="true">
                <div class="modal-dialog" role="document">
                  <div class="modal-content">
                    {{m.model_header("Dizi Güncelle","dizilerguncelModalLabel")}}
                      <form action="{{url_for('kisisel.dizi_guncelle', dizi_id=dizi.id)}}" method="POST">
                        {{m.input_group_modal("İsim","text","diziisimguncelle", dizi.isim)}}
                        {{m.input_group_modal("Çıkış Tarihi","text","dizicikistarihiguncelle", dizi.cikis_tarihi)}}
                        {{m.input_group_modal("Tur","text","diziturguncelle", dizi.tur)}}
                        {{m.input_group_modal("Son İzlenen","text","dizisonizlenenguncelle", dizi.son_izlenen)}}
                        {{m.input_group_modal("IMDB Puanı","number","diziimdbpuaniguncelle", dizi.imdb_puani)}}
                        {{m.input_group_modal("IMDB Link","text","diziimdblinkguncelle", dizi.imdb_link)}}
                        {{m.input_group_modal("Puanım","number","dizipuanimguncelle", dizi.mehmet_puan)}}
                        {% call m.select_modal("Dizi Durum","dizidurumguncelle") %}
                          <option value="Devam Ediyor" {{'selected' if dizi.ddurum == "Devam Ediyor" }}>Devam Ediyor</option>
                          <option value="Tamamlandı" {{'selected' if dizi.ddurum == "Tamamlandı" }}>Tamamlandı</option>
                        {% endcall %}
                        {{m.button_resimsiz("GÜNCELLE")}}
                      </form>
                    {{m.model_kapanis()}}
                  {{m.sil(dizi.id,"diziareadelete",url_for('kisisel.dizi_sil', dizi_id=dizi.id))}}
            </td>
          </tr>
        {% endfor %}
        </tbody>
      </table> 
    </div>
  </div>
</div>
<!-- TABLO JAVASCRIPT -->
{% block script %}
<script type="text/javascript" src="https://cdn.datatables.net/v/bs4/dt-1.10.23/fc-3.3.2/fh-3.1.8/r-2.2.7/sc-2.0.3/sl-1.3.1/datatables.min.js"></script>
<script src="{{url_for ('static', filename='js/datatable.js')}}"></script>
{% endblock script %}
{% endblock body %}

altan/templates/layout.html
<!doctype html>
<html lang="en">
  
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- JQuery -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
    <!-- Fontawesome -->
    {% block head %}{% endblock head%}
    <script src="https://kit.fontawesome.com/d97bad9e3a.js" crossorigin="anonymous"></script>
    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-BmbxuPwQa2lc/FVzBcNJ7UAyJxM6wuqIj61tLrc4wSX0szH/Ev+nYRRuWlolflfl" crossorigin="anonymous">
    <!-- Favicon -->
    <link rel="icon" type="image/png" href="{{url_for ('static', filename='img/favicon.ico')}}"/>
    <!-- Core CSS -->
    <link href="{{url_for ('static', filename='css/styles.css')}}" rel="stylesheet">
    <!-- Title -->
    <title> Altan - {% block title %}{% endblock%}</title>
  </head>

  <body>
    <!-- HEADER -->
    <header class="navbar navbar-dark sticky-top bg-dark flex-md-nowrap p-0 shadow">
      <a class="navbar-brand col-md-3 col-lg-2 me-0 px-3" href="{{url_for('main.index')}}">Mehmet Altan</a>
      <button class="navbar-toggler position-absolute d-md-none collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#sidebarMenu" aria-controls="sidebarMenu" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <input class="form-control form-control-dark w-100" type="text" placeholder="Not ..." aria-label="Search">
      <ul class="navbar-nav px-3">
        <li class="nav-item text-nowrap">
          <a class="nav-link" href="{{url_for('giris.log_out')}}">Çıkış Yap</a>
        </li>
      </ul>
      <img class="profile-foto" src="https://lh3.googleusercontent.com/ogw/ADGmqu9GJQ87AyAJWtsgkV5k1K4G4mFkTQyxs2v1AX6TdA=s83-c-mo" alt="profile">

    </header>
    {% import "macros.html" as m %}
    <div class="container-fluid">
      <div class="row">

        <!-- SIDEBAR -->
        <nav id="sidebarMenu" class="col-md-3 col-lg-2 d-md-block bg-light sidebar collapse">
          <div class="position-sticky pt-3">
            <ul class="nav flex-column">
              <li class="nav-item">
                <a class="list-group-item sidebar-separator-title text-muted d-flex align-items-center" href="{{url_for('main.index')}}">
                  <i class="fas fa-home"></i> Ana Sayfa
                </a>
              </li>
              <li class="list-group-item sidebar-separator-title text-muted d-flex align-items-center"><i class="far fa-building"></i>KOSGEB</li>
              {{m.nav_link("İşletme Bilgileri","fas fa-industry",url_for('main.isletme'))}}
              {{m.nav_link("Projeler","fas fa-tasks",url_for('main.projeleri_getir'))}}
              {{m.nav_link("Ödemeler","fas fa-money-bill-wave",url_for('main.odemeleri_getir'))}}
              {{m.nav_link("İşletmeler","fas fa-table",url_for('main.isletmeler'))}}
              {{m.nav_link("Bağlantılar","fas fa-external-link-alt",url_for('main.baglantilar'))}}
              <li class="list-group-item sidebar-separator-title text-muted d-flex align-items-center"><i class="fas fa-user-edit"></i>Kişisel</li>
              {{m.nav_link("Aile Bütçesi","fas fa-lira-sign",url_for('kisisel.hesap'))}}
              {{m.nav_link("Bütçe Sorgu","fas fa-chart-pie",url_for('kisisel.butce_sorgu'))}}
              {{m.nav_link("Yatırım Hesabı","fas fa-coins",url_for('kisisel.yatirim'))}}
              {{m.nav_link("Kitaplar","fas fa-book",url_for('kisisel.kitaplar'))}}
              {{m.nav_link("Diziler","fas fa-tv",url_for('kisisel.diziler'))}}
              {{m.nav_link("Filmler","fas fa-film",url_for('kisisel.filmler'))}}
            </ul>
          </div>
        </nav>

        <!-- CONTENT -->
        <main class="col-md-9 ms-sm-auto col-lg-10 px-md-4 pb-4"> 
          {% with messages = get_flashed_messages(with_categories=true) %}
          {% if messages %}
            {% for category, message in messages %}
          <div class="alert alert-{{ category }} text-center" role="alert" id="successMessage"> {{ message }}</div>
            {% endfor %}
          {% endif %}
          {% endwith %}

          {% block body %} {% endblock body %}
          
        </main>
      </div>
    </div>

    <!-- Bootstrap JavaScript -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/js/bootstrap.bundle.min.js" integrity="sha384-b5kHyXgcpbZJO/tY9Ul7kGkf1S0CWuKcCD38l8YkeH8z8QjE0GmW1gYU5S9FOnJ0" crossorigin="anonymous"></script>
    {% block script %}{% endblock script %}
    <!-- Core JavaScript -->
    <script src="{{url_for ('static', filename='js/alert.js')}}"></script>
  </body>
</html>

altan/templates/parametre.html
{% extends "layout.html" %} 

{% block body %}

{{m.ust_bilgi("Parametreler","")}}

<div class="row g-2 pb-2">

  <div class="col-md-2">
    <h6 class="pb-4">Kullanıcı İşlemleri</h6>
    <button type="button" class="btn btn-outline-secondary" data-toggle="modal" data-target="#kullaniciekle"><i class="fas fa-plus"></i>Ekle</button>
  </div>

  <div class="col-md-5">
    <h6 class="position-absolute">Program İsimleri</h6>
    <div class="d-flex d-flex justify-content-around">
      <button type="button" class="btn-outline-secondary" data-toggle="modal" data-target="#programekle"><i class="fas fa-plus"></i>Ekle</button>
    </div>
    <table class="table w-auto small align-middle">
      <thead>
        <tr>
          <th>#</th>
          <th>İsim</th>
          <th>İşlemler</th>
        </tr>
      </thead>
      <tbody>
      {% for program in defaults.programlar %}
        <tr>
          <td>{{loop.index}}</td>
          <td>{{program.isim}}</td>
          <td>
            <button type="submit" class="btn btn-outline-secondary btn-sm" data-toggle="modal" data-target="#my{{program.id}}"><span class="fas fa-pen"></button>                   
              <div class="modal fade" id="my{{program.id}}" tabindex="-1" role="dialog" aria-labelledby="#programgunModalLabel" aria-hidden="true">
                <div class="modal-dialog" role="document">
                  <div class="modal-content">
                    {{m.model_header("Program Güncelle","programgunModalLabel")}}
                      <form action="{{url_for('giris.parametreler_program_guncelle', program_id=program.id)}}" method="POST">
                        {{m.input_group_modal("Program Adı","text","programguncelle", program.isim)}}
                        {{m.button_resimsiz("GÜNCELLE")}}
                      </form>
                    {{m.model_kapanis()}}
              {{m.sil(program.id,"programareadelete",url_for('giris.parametreler_program_sil', program_id=program.id))}}
          </td>
        </tr>
      {% endfor %}
      </tbody>
    </table>
  </div>

  <div class="col-md-5">
    <h6 class="position-absolute">Destek İsimleri</h6>
    <div class="d-flex justify-content-around">
      <button type="button" class="btn-outline-secondary" data-toggle="modal" data-target="#destekekle"><i class="fas fa-plus"></i>Ekle</button>
    </div>
    <table class="table w-auto small align-middle">
      <thead>
        <tr>
          <th>#</th>
          <th>İsim</th>
          <th>İşlemler</th>
        </tr>
      </thead>
      <tbody> 
      {% for destek in defaults.destekler %}
        <tr>
          <td>{{loop.index}}</td>
          <td>{{destek.isim}}</td>
          <td>
            <button type="submit" class="btn btn-outline-secondary btn-sm" data-toggle="modal" data-target="#mi{{destek.id}}"><span class="fas fa-pen"></button>                   
              <div class="modal fade" id="mi{{destek.id}}" tabindex="-1" role="dialog" aria-labelledby="#destekgunModalLabel" aria-hidden="true">
                <div class="modal-dialog" role="document">
                  <div class="modal-content">
                    {{m.model_header("Destek Güncelle","destekgunModalLabel")}}
                      <form action="{{url_for('giris.parametreler_destek_guncelle', destek_id=destek.id)}}" method="POST">
                        {{m.input_group_modal("Destek Adı","text","destekguncelle", destek.isim)}}
                        {{m.button_resimsiz("GÜNCELLE")}}
                      </form>
                    {{m.model_kapanis()}}
              {{m.sil2(destek.id,"destekareadelete",url_for('giris.parametreler_destek_sil', destek_id=destek.id))}}          
          </td>
        </tr>
      {% endfor %}
      </tbody>
    </table>
  </div>
</div>

<!-- PROGRAM EKLEME MODAL -->
{{m.model_acilis("programekle","programModalLabel")}}
  {{m.model_header("Program Ekle","programModalLabel")}}
    <form action="{{url_for('giris.parametreler_program_ekle', sayi = defaults.sayi)}}" method="POST">
      {{m.input_group_modal("Program İsmi","text","programisimekle","")}}
      {{m.button_resimsiz("KAYDET")}}
    </form>
{{m.model_kapanis()}}
<!-- DESTEK EKLEME MODAL -->{{m.model_acilis("destekekle","destekModalLabel")}}
  {{m.model_header("Destek Ekle","destekModalLabel")}}
    <form action="{{url_for('giris.parametreler_destek_ekle')}}" method="POST">
      {{m.input_group_modal("Destek İsmi","text","destekisimekle","")}}
      {{m.button_resimsiz("KAYDET")}}
    </form>
{{m.model_kapanis()}}
<!-- KULLANICI EKLEME MODAL -->
{{m.model_acilis("kullaniciekle","kullaniciModalLabel")}}
  {{m.model_header("Kullanıcı Ekle","kullaniciModalLabel")}}
    <form action="{{url_for('giris.parametreler_kullanici_ekle')}}" method="POST">
      {{m.input_group_modal("Kullanıcı İsmi","text","kullaniciisimekle","")}}
      {{m.input_group_modal("Kullanıcı Şifresi","text","kullanicisifreekle","")}}
      {{m.button_resimsiz("KAYDET")}}
    </form>
{{m.model_kapanis()}}


{% endblock body %}